site_name: Rover Software
theme:
  name: material
nav:
  - Software: index.md
  - ROS Setup: ROS Setup.md
  - Git Setup: Git.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 0
  